### PR TITLE
Update image

### PR DESCRIPTION
**Pull request by dawnlarsson**
- Changes the old splash image to a new SVG
- Adds standard bottom links to Discord and Tauri Guides

### CODE REVIEW

**Review by simonhyll — DISMISSED** [review]

**Comment by Beanow** [comment]
jpeg? :scream:
image

I mean, it gets scaled down a lot, so this may be the more optimized way. Don't know.

**Comment by simonhyll** [comment]
JPEG is better to use from a size point of view if you don't have any transparency in the image

**Comment by dawnlarsson** [comment]
Don't know if gh .md supports SVG, in that case, could cut down size even further without the need for raster content...

**Comment by simonhyll** [comment]
Github supports SVG, but fonts can mess up if it's not just basic fonts that ALL browsers have installed. Not sure if you can get around that limitation with linking in fonts somehow, I dont believe you can. The best solution that's the most cross platform capable is just using PNG or JPEG, so don't spend time on adding SVG just for the sake of loading the README.md 0.1 second faster :)

**Comment by simonhyll** [comment]
If you turn all font based resources into paths it should work though

**Review by simonhyll — APPROVED** [review]

**Review by amrbashir — APPROVED** [review]

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
